/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Comrade1280 (https://sketchfab.com/comrade1280)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dss-harbinger-battle-cruiser-474f62d00ed54212b37f93ce91569c53
Title: D.S.S. Harbinger battle cruiser
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Craft(props) {
  const { nodes, materials } = useGLTF("/d.s.s._harbinger_battle_cruiser.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.024, -0.201]} rotation={[-1.5, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_panels_0.geometry}
          material={materials.panels}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_panelsDark_0.geometry}
          material={materials.panelsDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_techDark_0.geometry}
          material={materials.techDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_tech_0.geometry}
          material={materials.tech}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_techLight_0.geometry}
          material={materials.techLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_windows_0.geometry}
          material={materials.windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_whiteLight_0.geometry}
          material={materials.whiteLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_redLight_0.geometry}
          material={materials.redLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_greenLight_0.geometry}
          material={materials.greenLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_engineDark_0.geometry}
          material={materials.engineDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_yellowDecal_0.geometry}
          material={materials.yellowDecal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_whiteDecal_0.geometry}
          material={materials.whiteDecal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_redDecal_0.geometry}
          material={materials.redDecal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_nameDecal_0.geometry}
          material={materials.nameDecal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_engine_0.geometry}
          material={materials.engine}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_MainEngineGlow_0.geometry}
          material={materials.MainEngineGlow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HarbingerHull_RevEngineGlow_0.geometry}
          material={materials.RevEngineGlow}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/d.s.s._harbinger_battle_cruiser.glb");